version: '3.5'
services: 
  django_rest:
    build: .
    container_name: Api-farid
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

      
